### ISSUE TITLE
Postgres Agent mixes ec2 tags with database tags when run in a container

### ISSUE THREAD

**Issue by jamessammut** [DataDog/documentation#6588] opened 2020-02-05 22:03 UTC
**Describe the bug**
We cannot stop the datadog agent from capturing ec2 host information and merging it with the postgres monitor - this results in incorrect information being grouped in the UI.

I can find no way to stop the agent from automatically detecting that it is on an aws ec2 host and sending that meta information along with the postgres information.

This issue cause our monitors to alarm with incorrect host information making support of our databases and ec2 infrastructure difficult.

**To Reproduce**
1. Setup a postgres database v10.x
2. Package the datadog agent (v7.16.1) as a container with the settings to monitor the postgres database in step 1
3. Run this container on a separate ec2 host - setting `DD_HOSTNAME` to the hostname of the postgres server
4. Observe that the ec2 tags are added to the _host_ information gathered by the monitor, even though they are different hosts in the real world.

**Expected behavior**
A method to disable local server tag gathering (disable AWS Host checking) so that the metrics are clean for the database host.

**Screenshots**
![dashboard-showing-merged-information](https://user-images.githubusercontent.com/1061706/73888655-28961080-48c2-11ea-8a8a-ffb27c0b76ec.png)

**Additional context**
While we are in practice using an RDS Postgres service, we are not using the native aws integration, but running the monitors via a docker container on a docker swarm cluster.

**Comment by l0k0ms** [comment] 2020-02-10 12:07
Hello, 

Many thanks for this feedback. Could you submit this to our support team `support@datadoghq.com` ? They may have a work-around for your use-case.

Support team will make sure to notify us if there is a need for a public documentation update or if a new feature needs to be implemented.

I'm going to close this issue as it's not related to the Datadog public documentation, but feel free to re-open it if you think the issue is coming from the documentation.

Best regards,
Pierre

**Closed by l0k0ms** 2020-02-10 12:07 UTC
