### ISSUE TITLE
Custom Time Frames seems doesn't accept Unix seconds timestamp as suggested by documentation

### ISSUE THREAD

**Issue by plagov** [DataDog/documentation#12335] opened 2021-11-18 09:29 UTC
<!-- Is this a documentation issue? If not, and you need help with using Datadog, please contact our support team at https://docs.datadoghq.com/help/ --!>

## Documentation Page
https://docs.datadoghq.com/dashboards/guide/custom_time_frames/

## Issue Description
I think there's an issue with documentation for custom time frames. The documentation says that Unix seconds timestamp is accepted. When I paste in the Unix seconds when filtering traces, DataDog considers this value as milliseconds and filters out the time range with milliseconds.

**Comment by urseberry** [comment] 2021-11-20 17:34
Thanks for the feedback, @plagov! I am looking at this and will address it.

**Comment by urseberry** [comment] 2021-12-28 16:31
@plagov I looked into this and could not reproduce. I pasted in a range of Unix seconds on the APM->Traces page, and it filtered to the appropriate time period. Can you provide detailed instructions so I can reproduce the problem?

**Comment by urseberry** [comment] 2022-01-11 18:23
Closing this issue. Please reopen with detailed reproduction instructions if it recurs.

**Closed by urseberry** 2022-01-11 18:23 UTC
