### ISSUE TITLE
Keyboard short cuts not working on dashboards

### ISSUE THREAD

**Issue by brandonChenkovichServiceTitan** [DataDog/documentation#6025] opened 2019-11-20 15:16 UTC
**Describe the bug**
Keyboard short cuts to perform actions(f for tv mode) not working

**To Reproduce**
1. Go to any dashboard
2. press f
3. Nothing happens
4. Error in console:
Uncaught TypeError: Cannot read property 'isTvMode' of undefined
    at HTMLDocument.<anonymous> (dashboard.min.js:1)
    at HTMLDocument.dispatch (dashboard.min.js:1)
    at HTMLDocument.c (dashboard.min.js:1)
    at HTMLDocument.o (common.min.js:1)
    at r (common.min.js:1)
    at dashboard.min.js:1
    at l (common.min.js:1)
    at y.t._handleKey (common.min.js:1)
    at y.handleKey (common.min.js:1)
    at HTMLDocument.f (common.min.js:1)

**Expected behavior**
i hit f and tv mode is turned on

**Additional context**
Uncaught TypeError: Cannot read property 'isTvMode' of undefined
    at HTMLDocument.<anonymous> (dashboard.min.js:1)
    at HTMLDocument.dispatch (dashboard.min.js:1)
    at HTMLDocument.c (dashboard.min.js:1)
    at HTMLDocument.o (common.min.js:1)
    at r (common.min.js:1)
    at dashboard.min.js:1
    at l (common.min.js:1)
    at y.t._handleKey (common.min.js:1)
    at y.handleKey (common.min.js:1)
    at HTMLDocument.f (common.min.js:1)

**Comment by l0k0ms** [comment] 2019-11-22 09:07
Hello, 

Sorry about the inconvenient, the issue is now fixed :) 

Best regards,
Pierre

**Closed by l0k0ms** 2019-11-22 09:07 UTC
